#This target is used to compile cpp files
compile:
	g++ bank.cpp -o server -pthread -std=c++11
	g++ customer1.cpp -o client -std=c++11
#This target is used to clear object files
clean:
	rm -rf *.out server client
        
